apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaskhw
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DsRase/flaskHW.git
    targetRevision: ansible
    path: flaskhw
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: flaskhw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true